module Config
    class Settings
        REDESIGNED_BARNACLE_PORT = ENV["REDESIGNED_BARNACLE_PORT"] || 6009
        public_constant :REDESIGNED_BARNACLE_PORT

        REDESIGNED_BARNACLE_MIN_WORKERS = ENV["REDESIGNED_BARNACLE_MIN_WORKERS"] || 0
        public_constant :REDESIGNED_BARNACLE_MIN_WORKERS
        
        REDESIGNED_BARNACLE_MAX_WORKERS = ENV["REDESIGNED_BARNACLE_MAX_WORKERS"] || 4
        public_constant :REDESIGNED_BARNACLE_MAX_WORKERS 
    end
end